name: Daily push to Alienvault

on: workflow_dispatch
  #schedule:
    #- cron:  '20 03 * * *'

jobs:
  Finwarn:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_PRIVKEY_TO_REPORT_PRIVATE }}
        repository: maaaaz/report_malware
        path: ./REPORT_MALWARE_PRIVATE
    
    - name: Set $REPORT_MALWARE_PRIVATE environment variable for the rest of the workflow
      run: echo "REPORT_MALWARE_PRIVATE=$GITHUB_WORKSPACE/REPORT_MALWARE_PRIVATE" >> $GITHUB_ENV
    
    - name: What time is it ?
      run: |
        date -u
        TZ="Europe/Paris" date
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install prerequisites
      run: |
        sudo apt -qq update && sudo apt -qq install fd-find -y
        python -m pip install --upgrade pip

    - name: Install Netcraft dependencies
      run: |
        cd /tmp/
        wget -nv "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/netcraft.py"
        wget -nv "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/netcraft_requirements.txt"
        pip install -r ./netcraft_requirements.txt

    - name: Push yesterday Netcraft results to Alienvault
      run: |
        cd /tmp/

        TODAY_NETCRAFT_SUBS_FILE=$REPORT_MALWARE_PRIVATE/$(date --date="yesterday" '+%Y/%m/%Y-%m-%d/netcraft')/submissions.txt.gz
        ls -alh $TODAY_NETCRAFT_SUBS_FILE
        zcat $TODAY_NETCRAFT_SUBS_FILE | grep -i 'successfully report' | tr "'" '"'| jq -r '.uuid > /tmp/submissions.txt

        python3 -Wall /tmp/netcraft.py -a check -i /tmp/submissions.txt
        ls -alh output_malicious_*.txt
