name: Daily scans of daily new entries from public malware lists
on: workflow_dispatch
  #schedule:
    #- cron:  '00 01 * * *'

jobs:
  pub_malware_lists:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_PRIVKEY_TO_REPORT_PRIVATE }}
        repository: maaaaz/report_malware
        path: ./REPORT_MALWARE_PRIVATE
    
    - name: Set $REPORT_MALWARE_PRIVATE environment variable for the rest of the workflow
      run: echo "REPORT_MALWARE_PRIVATE=$GITHUB_WORKSPACE/REPORT_MALWARE_PRIVATE" >> $GITHUB_ENV
    
    - name: What time is it ?
      run: |
        date -u
        TZ="Europe/Paris" date
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Download daily data from different sources (CERT-PL, etc.)
      run: |
        cd /tmp/
        wget -nv https://hole.cert.pl/domains/v2/domains.json -O cert_pl_domains.json
        jq --raw-output -M '[.[] | select(.InsertDate [:10] >= (now-86400 | strftime("%Y-%m-%d")))] | .[] | .DomainAddress' cert_pl_domains.json > cert_pl_new_entries.txt

        wc ./cert_pl_new_entries.txt

    - name: Submit to CRDF
      env:
        SECRET_CRDF_API_KEY: ${{ secrets.SECRET_CRDF_API_KEY }}
        
      run: |
        cd /tmp/
        wget -nv "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/crdf.py"
        wget -nv "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/crdf_requirements.txt"
        pip install -r ./crdf_requirements.txt
        python /tmp/crdf.py -a submit -i "/tmp/cert_pl_new_entries.txt" 


    - name: Install Netcraft dependencies and download the script
      run: |
        cd /tmp/
        wget -nv "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/netcraft.py"
        wget -nv "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/netcraft_requirements.txt"
        pip install -r ./netcraft_requirements.txt

    - name: Submit to Netcraft
      continue-on-error: true
      env:
        SECRET_NETCRAFT_REPORT_MAIL: ${{ secrets.SECRET_NETCRAFT_REPORT_MAIL }}
        
      run: |
        cd /tmp/
        TZ="Europe/Paris" date
        (TZ="Europe/Paris" date && python /tmp/netcraft.py -a submit -i "/tmp/cert_pl_new_entries.txt";) > /dev/null


    - name: Install urlscan dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r $REPORT_MALWARE_PRIVATE/urlscan.io/requirements.txt
              
    - name: Scan on urlscan.io
      env: 
        SECRET_URLSCANIO_API_KEY: ${{ secrets.SECRET_URLSCANIO_API_KEY_FREELISTS }}
        SECRET_URLSCANIO_LOGIN: ${{ secrets.SECRET_URLSCANIO_LOGIN_FREELISTS }}
        SECRET_URLSCANIO_PASSWORD: ${{ secrets.SECRET_URLSCANIO_PASSWORD }}
                
      run: |
        cd /tmp/
        python -Wall "$REPORT_MALWARE_PRIVATE/urlscan.io/urlscan_io.py" -i "/tmp/cert_pl_new_entries.txt" -a submit
