name: Daily update finwarn

on: 
  workflow_dispatch
  #schedule:
    #- cron:  '45 07 * * *'

jobs:
  Finwarn:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_PRIVKEY_TO_REPORT_PRIVATE }}
        repository: maaaaz/report_malware
        path: ./REPORT_MALWARE_PRIVATE
    
    - name: Set $REPORT_MALWARE_PRIVATE environment variable for the rest of the workflow
      run: echo "REPORT_MALWARE_PRIVATE=$GITHUB_WORKSPACE/REPORT_MALWARE_PRIVATE" >> $GITHUB_ENV
    
    - name: What time is it ?
      run: |
        date -u
        TZ="Europe/Paris" date
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install prerequisites
      run: |
        cd "$REPORT_MALWARE_PRIVATE/finwarn/iosco/_source/"
        pip install -r iosco_alerts_requirements.txt

    - name: Update IOSCO alerts
      run: |
        cd "$REPORT_MALWARE_PRIVATE/finwarn/iosco/"
        cp ./iosco_alerts.csv.gz /tmp/
        
        cd ./source/
        python iosco_alerts.py -f latest -m previous

        cd ..
        zdiff ./iosco_alerts.csv.gz /tmp/iosco_alerts.csv.gz
