name: Daily push to Alienvault

on: workflow_dispatch
  #schedule:
    #- cron:  '20 03 * * *'

jobs:
  push_to_alienvault:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_PRIVKEY_TO_REPORT_PRIVATE }}
        repository: maaaaz/report_malware
        path: ./REPORT_MALWARE_PRIVATE
    
    - name: Set $REPORT_MALWARE_PRIVATE environment variable for the rest of the workflow
      run: echo "REPORT_MALWARE_PRIVATE=$GITHUB_WORKSPACE/REPORT_MALWARE_PRIVATE" >> $GITHUB_ENV
    
    - name: What time is it ?
      run: |
        date -u
        TZ="Europe/Paris" date
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install prerequisites
      run: |
        sudo apt -qq update && sudo apt -qq install fd-find -y
        python -m pip install --upgrade pip

    - name: Install Netcraft dependencies
      run: |
        cd /tmp/
        wget -nv "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/netcraft.py"
        wget -nv "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/netcraft_requirements.txt"
        pip install -r ./netcraft_requirements.txt

    - name: Collect yesterday Netcraft results 
      run: |
        cd /tmp/

        TODAY_NETCRAFT_SUBS_FILE=$REPORT_MALWARE_PRIVATE/$(date --date="yesterday" '+%Y/%m/%Y-%m-%d/netcraft')/submissions.txt.gz
        ls -alh $TODAY_NETCRAFT_SUBS_FILE
        zcat $TODAY_NETCRAFT_SUBS_FILE | grep -i 'successfully report' | tr "'" '"'| jq -r '.uuid' > /tmp/submissions.txt

        python3 -Wall /tmp/netcraft.py -a check -i /tmp/submissions.txt

    - name: How many results from yesterday ? 
      run: |
        cd /tmp/
        ls -alh output_malicious*.txt
        wc output_malicious*.txt

    - name: Push to AlienVault pulses
      env:
        SECRET_ALIENVAULT_API_KEY: ${{ secrets.SECRET_ALIENVAULT_API_KEY }}
        
      run: |
        cd /tmp/
        wget -nv "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/alienvault.py"
        wget -nv "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/alienvault_requirements.txt"
        pip install -r ./alienvault_requirements.txt
        python /tmp/alienvault.py -p "6547a9056b22ce65b94dcd87" -i "/tmp/output_malicious.txt" 
        python /tmp/alienvault.py -p "6547ab1dbcb543bdbe2573fa" -i "/tmp/output_malicious_credited.txt"
