name: Daily update finwarn

on: 
  schedule:
    - cron:  '20 00 * * *'

jobs:
  Finwarn:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_PRIVKEY_TO_REPORT_PRIVATE }}
        repository: maaaaz/report_malware
        path: ./REPORT_MALWARE_PRIVATE
    
    - name: Set $REPORT_MALWARE_PRIVATE environment variable for the rest of the workflow
      run: echo "REPORT_MALWARE_PRIVATE=$GITHUB_WORKSPACE/REPORT_MALWARE_PRIVATE" >> $GITHUB_ENV
    
    - name: What time is it ?
      run: |
        date -u
        TZ="Europe/Paris" date
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install prerequisites
      run: |
        sudo apt update && sudo apt install colordiff -y
        python -m pip install --upgrade pip
        
        cd "$REPORT_MALWARE_PRIVATE/finwarn/iosco/_source/"
        pip install -r "./iosco_alerts_requirements.txt"

    - name: Update IOSCO alerts
      run: |
        cd "$REPORT_MALWARE_PRIVATE/finwarn/iosco/"
        cp ./iosco_alerts.csv.gz /tmp/
        
        cd ./_source/
        python iosco_alerts.py -f latest -m previous

        cd ..
        wc ./iosco_alerts.csv.gz
        (colordiff <(zcat /tmp/iosco_alerts.csv.gz | sort -u) <(zcat ./iosco_alerts.csv.gz | sort -u)) || true

    - name: Git update
      run: |
        cd "$REPORT_MALWARE_PRIVATE/finwarn/iosco/"
        git pull --ff-only
        
        git config user.name finwarn-bot
        git config user.email github-actions@github.com
        git commit -m "updating bot - $(date --date="yesterday" '+%Y/%m/%d')" "./iosco_alerts.csv.gz"
        git pull --rebase
        git push
