name: Daily scans of daily new domain names from DNS registries 

on:
  schedule:
    - cron:  '00 01 * * *'

jobs:
  DNS_registries:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.SSH_PRIVKEY_TO_REPORT_PRIVATE }}
        repository: maaaaz/report_malware
        path: ./REPORT_MALWARE_PRIVATE
    
    - name: Set $REPORT_MALWARE_PRIVATE environment variable for the rest of the workflow
      run: echo "REPORT_MALWARE_PRIVATE=$GITHUB_WORKSPACE/REPORT_MALWARE_PRIVATE" >> $GITHUB_ENV
    
    - name: What time is it ?
      run: |
        date -u
        TZ="Europe/Paris" date
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        
    - name: Download daily data from different sources (AFNIC, dailynrdscan etc.)
      run: |
        cd /tmp/
        wget -nv https://www.afnic.fr/wp-media/ftp/domaineTLD_Afnic/$(date --date='yesterday' '+%Y%m%d')_CREA_{fr,re,pm,tf,wf,yt}.txt
        cat *_CREA_*  | grep -Pv '^#' | sort -u | grep --color=none . > new_ICANN_domains
        
        wget -nv "https://raw.githubusercontent.com/maaaaz/dnsdumps/main/daily/today_new.gz" -O "./dailynrdscan_today_new.gz"
        zcat "./dailynrdscan_today_new.gz" >> new_ICANN_domains

    - name: Resolve data
      run: |
        cd /tmp/
        # testing
        #echo 'toto.fr' > ./new_ICANN_domains
        
        wget -nv "https://github.com/maaaaz/zmapproject_binaries/raw/main/linux-x64/zdns/zdns" && chmod u+x ./zdns
        
        time ./zdns --input-file "/tmp/new_ICANN_domains" --name-servers "9.9.9.9,149.112.112.112,1.1.1.1,8.8.8.8,1.0.0.1,208.67.222.222,208.67.220.123" --output-file temp_zdns_results_A A
        ls -alh temp_zdns_results_A && wc temp_zdns_results_A

        time ./zdns --input-file "/tmp/new_ICANN_domains" --name-servers "9.9.9.9,149.112.112.112,1.1.1.1,8.8.8.8,1.0.0.1,208.67.222.222,208.67.220.123" --output-file temp_zdns_results_AAAA AAAA
        ls -alh temp_zdns_results_AAAA && wc temp_zdns_results_AAAA

        cat temp_zdns_results_* > ./zdns_results_raw.txt
        ls -alh zdns_results_raw.txt && wc zdns_results_raw.txt

        jq --raw-output -M '.data | select (.answers != null) | .answers | .[] | select(.type == "A" or .type == "AAAA") | .name' ./zdns_results_raw.txt | sort -u | shuf > ./zdns_results.txt
        sed -i -e 's/^/http:\/\//' ./zdns_results_with_http.txt

        ls -alh ./zdns_results_with_http.txt && wc ./zdns_results_with_http.txt
        head zdns_results.txt
        head zdns_results_with_http.txt

    
    - name: Git pull $REPORT_MALWARE_PRIVATE
      run: |
        cd $REPORT_MALWARE_PRIVATE
        git pull --ff-only
        
    - name: Install Netcraft dependencies and download the script
      run: |
        cd /tmp/
        wget -nv "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/netcraft.py"
        wget -nv "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/netcraft_requirements.txt"
        pip install -r ./netcraft_requirements.txt
        
    - name: Submit to Netcraft
      continue-on-error: true
      env:
        SECRET_NETCRAFT_REPORT_MAIL: ${{ secrets.SECRET_NETCRAFT_REPORT_MAIL }}
        
      run: |
        cd $REPORT_MALWARE_PRIVATE
        git pull --ff-only
        
        TODAY_NETCRAFT_SUBS_DIR=$REPORT_MALWARE_PRIVATE/$(date '+%Y/%m/%Y-%m-%d/netcraft')
        mkdir -p "$TODAY_NETCRAFT_SUBS_DIR"
        TODAY_NETCRAFT_SUBS_FILE=$TODAY_NETCRAFT_SUBS_DIR/submissions.txt
                
        cd /tmp/
        TZ="Europe/Paris" date
        (TZ="Europe/Paris" date && python /tmp/netcraft.py -a submit -i "/tmp/zdns_results_with_http.txt";) > /tmp/temp_netcraft_results
        
        cd $REPORT_MALWARE_PRIVATE
        git pull --ff-only
        cat /tmp/temp_netcraft_results >> $TODAY_NETCRAFT_SUBS_FILE
        
        # -- git stuff
        cd $REPORT_MALWARE_PRIVATE
        git config user.name netcraft-subs-bot
        git config user.email github-actions@github.com
        git add $TODAY_NETCRAFT_SUBS_FILE
        git commit -m "netcraft sub of ICANN daily new domains" $TODAY_NETCRAFT_SUBS_FILE
        git pull --rebase
        git push
        
    - name: Submit to CRDF
      env:
        SECRET_CRDF_API_KEY: ${{ secrets.SECRET_CRDF_API_KEY }}
        
      run: |
        cd /tmp/
        wget -nv "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/crdf.py"
        wget -nv "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/crdf_requirements.txt"
        pip install -r ./crdf_requirements.txt
        python /tmp/crdf.py -a submit -i "/tmp/zdns_results.txt"  

    - name: Install pylookyloo
      run: |
        pip install pylookyloo
        
    - name: Scan to Lookyloo
      run: |
        awk '{print "http://"$1"\n""https://"$1}' "/tmp/zdns_results.txt" > "/tmp/new_ICANN_domains_with_existing_IPv4_or_IPv6_expanded"
        parallel -a "/tmp/new_ICANN_domains_with_existing_IPv4_or_IPv6_expanded" 'lookyloo --listing --query {} >> /tmp/lookyloo_scans'
        head "/tmp/lookyloo_scans"
