name: Semihourly watch of usual suspects on urlscan.io and submit them

on: 
  schedule:
    - cron:  '1,31 * * * *'

jobs:
  semihourly_report:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_PRIVKEY_TO_REPORT_PRIVATE }}
        repository: maaaaz/report_malware
        path: ./REPORT_MALWARE_PRIVATE
    
    - name: Set $REPORT_MALWARE_PRIVATE environment variable for the rest of the workflow
      run: echo "REPORT_MALWARE_PRIVATE=$GITHUB_WORKSPACE/REPORT_MALWARE_PRIVATE" >> $GITHUB_ENV
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: What time is it ?
      run: |
        date -u
        TZ="Europe/Paris" date

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r $REPORT_MALWARE_PRIVATE/urlscan.io/requirements.txt

    - name: Scan the current regular watched queries on urlscan.io
      env: 
        SECRET_URLSCANIO_API_KEY: ${{ secrets.SECRET_URLSCANIO_API_KEY_WATCH }}
        SECRET_URLSCANIO_LOGIN: ${{ secrets.SECRET_URLSCANIO_LOGIN_WATCH }}
        SECRET_URLSCANIO_PASSWORD: ${{ secrets.SECRET_URLSCANIO_PASSWORD_WATCH }}
                
      run: |
        cd $REPORT_MALWARE_PRIVATE
        git pull --ff-only
        
        # -- watch_queries.txt
        cd "$REPORT_MALWARE_PRIVATE/urlscan.io/watch/"
        python $REPORT_MALWARE_PRIVATE/urlscan.io/urlscan_io.py -a search -i "./watch_queries.txt" -oq results_temp.txt
        grep -v -F -f ./results_queries.txt ./results_temp.txt > /tmp/diff_temp_master
        
        cat "./results_queries.txt" "/tmp/diff_temp_master" | sort -u > /tmp/temp_new_results_queries.txt
        cat /tmp/temp_new_results_queries.txt > "./results_queries.txt"

    - name: Scan the current vague watched queries on urlscan.io
      env: 
        SECRET_URLSCANIO_API_KEY: ${{ secrets.SECRET_URLSCANIO_API_KEY_WATCH_2 }}
        SECRET_URLSCANIO_LOGIN: ${{ secrets.SECRET_URLSCANIO_LOGIN_WATCH_2 }}
        SECRET_URLSCANIO_PASSWORD: ${{ secrets.SECRET_URLSCANIO_PASSWORD_WATCH_2 }}
        
      run: |
        # -- watch_queries_vague.txt
        cd "$REPORT_MALWARE_PRIVATE/urlscan.io/watch/"
        python $REPORT_MALWARE_PRIVATE/urlscan.io/urlscan_io.py -a search -i "./watch_queries_vague.txt" -oq results_temp_vague.txt
        
        cp "./results_queries_vague.txt.gz" "/tmp/results_queries_vague.txt.gz"
        gunzip "/tmp/results_queries_vague.txt.gz"
        grep -v -F -f /tmp/results_queries_vague.txt "./results_temp_vague.txt" > "/tmp/diff_temp_master_vague"
        
        cat "/tmp/results_queries_vague.txt" "/tmp/diff_temp_master_vague" | sort -u | gzip > "/tmp/temp_new_results_queries_vague.txt.gz"
        mv -f "/tmp/temp_new_results_queries_vague.txt.gz" "./results_queries_vague.txt.gz"

    - name: Push to GitHub
      continue-on-error: true
      run: |
        # -- git stuff
        cd "$REPORT_MALWARE_PRIVATE/urlscan.io/watch/"
        
        git config user.name urlscan-scraping-bot
        git config user.email github-actions@github.com
        git commit -m "semihourly urlscan watch regular and vague to github" "./results_queries.txt" "./results_queries_vague.txt.gz"
        git pull --rebase
        git push
        
    - name: Install Netcraft dependencies
      run: |
        cd /tmp/
        wget -nv "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/netcraft.py"
        wget -nv "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/netcraft_requirements.txt"
        pip install -r ./netcraft_requirements.txt
        
    - name: Submit watched queries results to Netcraft
      continue-on-error: true
      env:
        SECRET_NETCRAFT_REPORT_MAIL: ${{ secrets.SECRET_NETCRAFT_REPORT_MAIL }}
        
      run: |
        cd $REPORT_MALWARE_PRIVATE
        git pull
        
        TODAY_NETCRAFT_SUBS_DIR=$REPORT_MALWARE_PRIVATE/$(date '+%Y/%m/%Y-%m-%d/netcraft')
        mkdir -p "$TODAY_NETCRAFT_SUBS_DIR"
        TODAY_NETCRAFT_SUBS_FILE=$TODAY_NETCRAFT_SUBS_DIR/submissions.txt
        
        cd /tmp/
        TZ="Europe/Paris" date
        (TZ="Europe/Paris" date && python /tmp/netcraft.py -a submit -i "/tmp/diff_temp_master";) > /tmp/temp_netcraft_results_regular
        (TZ="Europe/Paris" date && python /tmp/netcraft.py -a submit -i "/tmp/diff_temp_master_vague";) > /tmp/temp_netcraft_results_vague
        
        cd $REPORT_MALWARE_PRIVATE
        git pull --ff-only
        cat /tmp/temp_netcraft_results_* >> $TODAY_NETCRAFT_SUBS_FILE
        
        # -- git stuff
        cd $REPORT_MALWARE_PRIVATE
        git config user.name netcraft-subs-bot
        git config user.email github-actions@github.com
        git add $TODAY_NETCRAFT_SUBS_FILE
        git commit -m "semihourly urlscan watch regular and vague to netcraft" $TODAY_NETCRAFT_SUBS_FILE
        git pull --rebase
        git push

    - name: Submit to CRDF
      env:
        SECRET_CRDF_API_KEY: ${{ secrets.SECRET_CRDF_API_KEY }}
        
      run: |
        cd /tmp/
        wget -nv "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/crdf.py"
        wget -nv "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/crdf_requirements.txt"
        pip install -r ./crdf_requirements.txt
        python /tmp/crdf.py -a submit -i "/tmp/diff_temp_master"  
        python /tmp/crdf.py -a submit -i "/tmp/diff_temp_master_vague"
