name: Semihourly watch of usual suspects on urlscan.io and submit them

on: [push]
  #schedule:
    #- cron:  '1,31 * * * *'

jobs:
  urlscan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_PRIVKEY_TO_REPORT_PRIVATE }}
        repository: maaaaz/report_malware
        path: ./REPORT_MALWARE_PRIVATE
    
    - name: Set $REPORT_MALWARE_PRIVATE environment variable for the rest of the workflow
      run: echo "REPORT_MALWARE_PRIVATE=$GITHUB_WORKSPACE/REPORT_MALWARE_PRIVATE" >> $GITHUB_ENV
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        echo '----'
        date -u
        TZ="Europe/Paris" date
        echo '----'
        
        python -m pip install --upgrade pip
        pip install -r $REPORT_MALWARE_PRIVATE/urlscan.io/requirements.txt

    - name: Scan the current regular watched queries on urlscan.io
      env: 
        SECRET_URLSCANIO_API_KEY: ${{ secrets.SECRET_URLSCANIO_API_KEY_WATCH }}
        SECRET_URLSCANIO_LOGIN: ${{ secrets.SECRET_URLSCANIO_LOGIN_WATCH }}
        SECRET_URLSCANIO_PASSWORD: ${{ secrets.SECRET_URLSCANIO_PASSWORD_WATCH }}
                
      run: |
        # -- watch_queries.txt
        cd "$REPORT_MALWARE_PRIVATE/urlscan.io/watch/"
        python $REPORT_MALWARE_PRIVATE/urlscan.io/urlscan_io.py -a search -i "./watch_queries.txt" -oq results_temp.txt
        grep -v -F -f ./results_queries.txt ./results_temp.txt > /tmp/diff_temp_master
        
        cat "./results_queries.txt" "/tmp/diff_temp_master" | sort -u > /tmp/temp_new_results_queries.txt
        cat /tmp/temp_new_results_queries.txt > "./results_queries.txt"

    - name: Scan the current vague watched queries on urlscan.io
      env: 
        SECRET_URLSCANIO_API_KEY: ${{ secrets.SECRET_URLSCANIO_API_KEY_WATCH_2 }}
        SECRET_URLSCANIO_LOGIN: ${{ secrets.SECRET_URLSCANIO_LOGIN_WATCH_2 }}
        SECRET_URLSCANIO_PASSWORD: ${{ secrets.SECRET_URLSCANIO_PASSWORD_WATCH_2 }}
        
      run: |
        # -- watch_queries_vague.txt
        cd "$REPORT_MALWARE_PRIVATE/urlscan.io/watch/"
        python $REPORT_MALWARE_PRIVATE/urlscan.io/urlscan_io.py -a search -i "./watch_queries_vague.txt" -oq results_temp_vague.txt
        
        cp "./results_queries_vague.txt.gz" "/tmp/results_queries_vague.txt.gz"
        gunzip "/tmp/results_queries_vague.txt.gz"
        grep -v -F -f /tmp/results_queries_vague.txt "./results_temp_vague.txt" > "/tmp/diff_temp_master_vague"
        
        cat "/tmp/results_queries_vague.txt" "/tmp/diff_temp_master_vague" | sort -u | gzip > "/tmp/temp_new_results_queries_vague.txt.gz"
        mv -f "/tmp/temp_new_results_queries_vague.txt.gz" "./results_queries_vague.txt.gz"

    - name: Push to GitHub
      run: |
        # -- git stuff
        cd "$REPORT_MALWARE_PRIVATE/urlscan.io/watch/"
        
        git config user.name urlscan-scraping-bot
        git config user.email github-actions@github.com
        git pull
        git commit -m "hourly scan urlscan.io" "./results_queries.txt" "./results_queries_vague.txt.gz"
        git push
        
        
    - name: Install Netcraft dependencies
      run: |
        cd /tmp/
        wget "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/netcraft_requirements.txt"
        pip install -r ./netcraft_requirements.txt
        
    - name: Submit watched queries results to Netcraft
      env:
        SECRET_NETCRAFT_REPORT_MAIL: ${{ secrets.SECRET_NETCRAFT_REPORT_MAIL }}
        
      run: |       
        git pull
        
        TODAY_NETCRAFT_SUBS_FILE=/tmp/$(date '+%Y/%m/%Y-%m-%d/netcraft')/submissions.txt
        
        cd /tmp/
        wget "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/netcraft.py"
        (TZ="Europe/Paris" date && python /tmp/netcraft.py -a submit -i "/tmp/diff_temp_master";) >> $TODAY_NETCRAFT_SUBS_FILE
        
        (TZ="Europe/Paris" date && python /tmp/netcraft.py -a submit -i "/tmp/diff_temp_master_vague";) >> $TODAY_NETCRAFT_SUBS_FILE
        
        git config user.name urlscan-scraping-bot
        git config user.email github-actions@github.com
        git pull
        git add $TODAY_NETCRAFT_SUBS_FILE
        git commit -m "hourly scan urlscan.io" "./results_queries.txt" "./results_queries_vague.txt.gz" $TODAY_NETCRAFT_SUBS_FILE        
        git push
        
