name: Semihourly watch of suspicious new domains from certstream and submit them

on: 
  schedule:
    - cron:  '15,45 * * * *'

jobs:
  semihourly_report_certstream:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.SSH_PRIVKEY_TO_REPORT_PRIVATE }}
        repository: maaaaz/report_malware
        path: ./REPORT_MALWARE_PRIVATE
    
    - name: Set $REPORT_MALWARE_PRIVATE environment variable for the rest of the workflow
      run: echo "REPORT_MALWARE_PRIVATE=$GITHUB_WORKSPACE/REPORT_MALWARE_PRIVATE" >> $GITHUB_ENV
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: What time is it ?
      run: |
        date -u
        TZ="Europe/Paris" date
    
    - name: Install certstream
      run: |
        python -m pip install --upgrade pip
        pip install certstream
        
    - name: Run certstream for 30 minutes
      run: |
        cd /tmp/
        
        # -- temp bug fix from certstream unavailability
        #time (timeout -s 9 31m bash -c "certstream --json | jq -r '.data.leaf_cert.all_domains[]' > ./certstream_dump_raw" || true)

        wget -nv "https://github.com/d-Rickyy-b/certstream-server-go/releases/download/v1.5.1/certstream-server-go_1.5.1_linux_amd64" -O "certstream-server" && chmod u+x "./certstream-server"
        cat > /tmp/config.yaml <<EOL
         webserver:
          listen_addr: "127.0.0.1"
          listen_port: 8080
          full_url: "/full-stream"
          lite_url: "/"
          domains_only_url: "/domains-only"
          cert_path: ""
          cert_key_path: ""
        
        prometheus:
          enabled: false
          listen_addr: "0.0.0.0"
          listen_port: 8080
          metrics_url: "/metrics"
          expose_system_metrics: false
          real_ip: false
          whitelist:
            - "127.0.0.1/8"
        EOL
        nohup ./certstream-server > nohup.out 2> nohup.err < /dev/null &
        
        time (timeout -s 9 31m bash -c "certstream --url ws://127.0.0.1:8080 --json | jq -r '.data.leaf_cert.all_domains[]' > ./certstream_dump_raw" || true)
        sed 's/^\*\.//g' "./certstream_dump_raw" | sort -u > "./certstream_dump"
        
        echo '[+] results certstream'
        wc "./certstream_dump"
        ls -alh "./certstream_dump"
        head "./certstream_dump"
    
    - name: Install opensquat
      run: |
        cd /tmp/
        git clone https://github.com/maaaaz/opensquat.git
        pip install -r ./opensquat/requirements.txt
    
    - name: Run opensquat
      run: |
        cd /tmp/opensquat/
        python opensquat.py -d "/tmp/certstream_dump" -k "$REPORT_MALWARE_PRIVATE/keywords/keywords.txt" > /dev/null
        
        echo '[+] results opensquat'
        mv "./results.txt" "./results_unsorted.txt"
        sort -u "./results_unsorted.txt" > "./results.txt"
        ls -al "./results.txt"
        wc "./results.txt"
        head "./results.txt"

    - name: Resolve data
      run: |
        cd /tmp/
        wget -nv "https://github.com/maaaaz/zmapproject_binaries/raw/main/linux-x64/zdns/zdns" && chmod u+x ./zdns
        
        time ./zdns --input-file "/tmp/opensquat/results.txt" --name-servers "9.9.9.9,149.112.112.112,1.1.1.1,8.8.8.8,1.0.0.1,208.67.222.222,208.67.220.123" --output-file temp_zdns_results_A A
        ls -alh temp_zdns_results_A && wc temp_zdns_results_A

        time ./zdns --input-file "/tmp/opensquat/results.txt" --name-servers "9.9.9.9,149.112.112.112,1.1.1.1,8.8.8.8,1.0.0.1,208.67.222.222,208.67.220.123" --output-file temp_zdns_results_AAAA AAAA
        ls -alh temp_zdns_results_AAAA && wc temp_zdns_results_AAAA

        cat temp_zdns_results_* > ./zdns_results_raw.txt
        ls -alh zdns_results_raw.txt && wc zdns_results_raw.txt

        jq --raw-output -M '.data | select (.answers != null) | .answers | .[] | select(.type == "A" or .type == "AAAA") | .name' ./zdns_results_raw.txt | sort -u | shuf > ./zdns_results.txt
        sed -i -e 's/^/http:\/\//' ./zdns_results.txt

        ls -alh zdns_results.txt && wc zdns_results.txt
        head zdns_results.txt
    
    - name: Install Netcraft dependencies
      run: |
        cd /tmp/
        wget -nv "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/netcraft.py"
        wget -nv "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/netcraft_requirements.txt"
        pip install -r ./netcraft_requirements.txt
        
    - name: Submit watched queries results to Netcraft
      env:
        SECRET_NETCRAFT_REPORT_MAIL: ${{ secrets.SECRET_NETCRAFT_REPORT_MAIL }}
        
      run: |
        cd $REPORT_MALWARE_PRIVATE
        TODAY_NETCRAFT_SUBS_DIR=$REPORT_MALWARE_PRIVATE/$(date '+%Y/%m/%Y-%m-%d/netcraft')
        mkdir -p "$TODAY_NETCRAFT_SUBS_DIR"
        TODAY_NETCRAFT_SUBS_FILE=$TODAY_NETCRAFT_SUBS_DIR/submissions.txt
        
        cd /tmp/
        TZ="Europe/Paris" date
        #(TZ="Europe/Paris" date && python /tmp/netcraft.py -a submit -i "/tmp/opensquat/results.txt";) > /tmp/temp_netcraft_results
        (TZ="Europe/Paris" date && python /tmp/netcraft.py -a submit -i "/tmp/zdns_results.txt";) > /tmp/temp_netcraft_results
        
        cd $REPORT_MALWARE_PRIVATE
        git pull --ff-only
        cat /tmp/temp_netcraft_results >> $TODAY_NETCRAFT_SUBS_FILE
        
        # -- git stuff
        cd $REPORT_MALWARE_PRIVATE
        git config user.name netcraft-subs-bot
        git config user.email github-actions@github.com
        git add $TODAY_NETCRAFT_SUBS_FILE
        git commit -m "semihourly certstream scan to netcraft" $TODAY_NETCRAFT_SUBS_FILE
        git pull --rebase
        git push
