name: Semihourly watch of suspicious new domains from certstream and submit them

on: [push]
  #schedule:
    #- cron:  '1,31 * * * *'

jobs:
  semihourly_report_certstream:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_PRIVKEY_TO_REPORT_PRIVATE }}
        repository: maaaaz/report_malware
        path: ./REPORT_MALWARE_PRIVATE
    
    - name: Set $REPORT_MALWARE_PRIVATE environment variable for the rest of the workflow
      run: echo "REPORT_MALWARE_PRIVATE=$GITHUB_WORKSPACE/REPORT_MALWARE_PRIVATE" >> $GITHUB_ENV
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: What time is it ?
      run: |
        date -u
        TZ="Europe/Paris" date
    
    - name: Install certstream dependencies and run it for 30 minutes
      run: |
        python -m pip install --upgrade pip
        pip install certstream
        
        cd /tmp/
        time timeout -s 9 1m bash -c "certstream --json | jq -r '.data.leaf_cert.all_domains[]' > ./certstream_dump_raw" ; exit 0
        sed 's/^\*\.//g' "./certstream_dump_raw" | sort -u > "./certstream_dump"
    
    - name: Install opensquat dependencies and run it 
      run: |
        cd /tmp/
        git clone https://github.com/maaaaz/opensquat.git 
        cd opensquat
        pip install -r requirements.txt
        python opensquat.py -d "/tmp/certstream_dump" -k "$REPORT_MALWARE_PRIVATE/keywords/keywords.txt" 2> /dev/nulll
        ls -al results.txt
        head results.txt
        
    - name: Install Netcraft dependencies
      run: |
        cd /tmp/
        wget -nv "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/netcraft.py"
        wget -nv "https://github.com/maaaaz/red.flag.domains-publications/raw/main/_resources/netcraft_requirements.txt"
        pip install -r ./netcraft_requirements.txt
        
    - name: Submit watched queries results to Netcraft
      env:
        SECRET_NETCRAFT_REPORT_MAIL: ${{ secrets.SECRET_NETCRAFT_REPORT_MAIL }}
        
      run: |
        TZ="Europe/Paris" date
        (TZ="Europe/Paris" date && python /tmp/netcraft.py -a submit -i "/tmp/opensquat/results.txt";) >> $TODAY_NETCRAFT_SUBS_FILE
        
        # -- git stuff
        cd $REPORT_MALWARE_PRIVATE
        git config user.name netcraft-subs-bot
        git config user.email github-actions@github.com
        git pull
        git add $TODAY_NETCRAFT_SUBS_FILE
        git commit -m "netcraft sub of certstream semihourly new domains" $TODAY_NETCRAFT_SUBS_FILE
        git push
