name: Semihourly watch of usual suspects on urlscan.io and submit them

on: [push]
  #schedule:
    #- cron:  '1,31 * * * *'

jobs:
  urlscan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_PRIVKEY_TO_REPORT_PRIVATE }}
        repository: maaaaz/report_malware
        path: ./REPORT_MALWARE_PRIVATE
    
    - name: Set $REPORT_MALWARE_PRIVATE environment variable for the rest of the workflow
      run: echo "REPORT_MALWARE_PRIVATE=$GITHUB_WORKSPACE/REPORT_MALWARE_PRIVATE" >> $GITHUB_ENV
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        date -u
        TZ="Europe/Paris" date
        python -m pip install --upgrade pip
        pip install -r $REPORT_MALWARE_PRIVATE/urlscan.io/requirements.txt

    - name: Scan the current regular watched queries on urlscan.io
      env: 
        SECRET_URLSCANIO_API_KEY: ${{ secrets.SECRET_URLSCANIO_API_KEY_WATCH }}
        SECRET_URLSCANIO_LOGIN: ${{ secrets.SECRET_URLSCANIO_LOGIN_WATCH }}
        SECRET_URLSCANIO_PASSWORD: ${{ secrets.SECRET_URLSCANIO_PASSWORD_WATCH }}
                
      run: |
        # -- watch_queries.txt
        cd "$REPORT_MALWARE_PRIVATE/urlscan.io/watch/"
        python $REPORT_MALWARE_PRIVATE/urlscan.io/urlscan_io.py -a search -i "./watch_queries.txt" -oq results_temp.txt
        grep -v -F -f ./results_queries.txt ./results_temp.txt > /tmp/diff_temp_master
        
        cat "./results_queries.txt" "/tmp/diff_temp_master" | sort -u > /tmp/temp_new_results_queries.txt
        cat /tmp/temp_new_results_queries.txt > "./results_queries.txt"
